Fix ``faker`` in requirements (#76)
Tests failed with
```
ImportError: The ``fake-factory`` package is now called ``Faker``.

Please update your requirements.
```
The `fake-factory` package was deprecated on December 15th, 2016.
Use the `Faker` package instead.